version: "3.1"
name: project_flask
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - project1_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin_db:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db    
  app:
    build: .
    volumes:
      - .:/backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  project1_data:
  pgadmin_db:
  